name: validate-all-prs-on-trigger

on:
  workflow_dispatch

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/validate-all-prs-on-trigger
        with:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}